name: Daily Supabase Correlation Update

on:
  schedule:
    # 매일 UTC 기준 오전 8시 30분 실행
    # UTC+9 오전 8시 30분은 UTC 기준으로 이전 날짜의 오후 11시 30분입니다. (8:30 - 9시간 = -0:30, 즉 전날 23:30)
    # 분 시간 일 월 요일
    # 30 23 * * *
    - cron: '30 23 * * *'
  workflow_dispatch: # 수동 실행을 위한 트리거 (선택 사항)

jobs:
  run_correlation_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # 또는 '3.10', '3.11' 등 원하는 Python 버전 지정

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas supabase

      - name: Run correlation script
        env:
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: python run_correlations.py