#매일 주식 데이터를 자동 업로드하는 용도
# .github/workflows/stock_data_fetch.yml

name: Fetch Daily Stock Data

on:
  workflow_dispatch: # 수동 실행을 위한 옵션
  schedule:
    - cron: '0 23 * * *' # UTC 기준 매일 23:00 (한국 시간 오전 8:00)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # 원하시는 파이썬 버전으로 설정

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # 루트 디렉토리의 requirements.txt 사용

      - name: Run Python script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python 주식데이터/주식추출_매일_jsw.py
