#매일 주식 데이터를 자동 업로드하는 용도
# .github/workflows/stock_data_fetch.yml

name: Daily Korea.S Stock Data Update

on:
  workflow_dispatch: # 수동 실행을 위한 옵션
  schedule:
    - cron: '0 7 * * *' # UTC 기준 매일 07:00 (한국 시간 오후 16:00)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
      - name: Run Python script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python 주식데이터/주식추출_매일_jsw.py
